// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: platform/report.proto

package platform

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An async export job record.
type ExportJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExportId       string                 `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExportFileName string                 `protobuf:"bytes,3,opt,name=export_file_name,json=exportFileName,proto3" json:"export_file_name,omitempty"`
	ExportType     ExportType             `protobuf:"varint,4,opt,name=export_type,json=exportType,proto3,enum=platform.ExportType" json:"export_type,omitempty"`
	Status         ExportStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=platform.ExportStatus" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ExportJob) Reset() {
	*x = ExportJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportJob) ProtoMessage() {}

func (x *ExportJob) ProtoReflect() protoreflect.Message {
	mi := &file_platform_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportJob.ProtoReflect.Descriptor instead.
func (*ExportJob) Descriptor() ([]byte, []int) {
	return file_platform_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExportJob) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *ExportJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportJob) GetExportFileName() string {
	if x != nil {
		return x.ExportFileName
	}
	return ""
}

func (x *ExportJob) GetExportType() ExportType {
	if x != nil {
		return x.ExportType
	}
	return ExportType_EXPORT_TYPE_UNSPECIFIED
}

func (x *ExportJob) GetStatus() ExportStatus {
	if x != nil {
		return x.Status
	}
	return ExportStatus_EXPORT_STATUS_UNSPECIFIED
}

func (x *ExportJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExportJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ExportJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListExportJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   string       `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExportType ExportType   `protobuf:"varint,2,opt,name=export_type,json=exportType,proto3,enum=platform.ExportType" json:"export_type,omitempty"`
	Status     ExportStatus `protobuf:"varint,3,opt,name=status,proto3,enum=platform.ExportStatus" json:"status,omitempty"`
	Limit      uint32       `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset     uint32       `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListExportJobsRequest) Reset() {
	*x = ListExportJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExportJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportJobsRequest) ProtoMessage() {}

func (x *ListExportJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportJobsRequest.ProtoReflect.Descriptor instead.
func (*ListExportJobsRequest) Descriptor() ([]byte, []int) {
	return file_platform_report_proto_rawDescGZIP(), []int{1}
}

func (x *ListExportJobsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListExportJobsRequest) GetExportType() ExportType {
	if x != nil {
		return x.ExportType
	}
	return ExportType_EXPORT_TYPE_UNSPECIFIED
}

func (x *ListExportJobsRequest) GetStatus() ExportStatus {
	if x != nil {
		return x.Status
	}
	return ExportStatus_EXPORT_STATUS_UNSPECIFIED
}

func (x *ListExportJobsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExportJobsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListExportJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount uint32       `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Jobs       []*ExportJob `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *ListExportJobsResponse) Reset() {
	*x = ListExportJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_report_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExportJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportJobsResponse) ProtoMessage() {}

func (x *ListExportJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_report_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportJobsResponse.ProtoReflect.Descriptor instead.
func (*ListExportJobsResponse) Descriptor() ([]byte, []int) {
	return file_platform_report_proto_rawDescGZIP(), []int{2}
}

func (x *ListExportJobsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListExportJobsResponse) GetJobs() []*ExportJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type DownloadExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExportId string `protobuf:"bytes,1,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *DownloadExportRequest) Reset() {
	*x = DownloadExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_report_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportRequest) ProtoMessage() {}

func (x *DownloadExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_report_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportRequest.ProtoReflect.Descriptor instead.
func (*DownloadExportRequest) Descriptor() ([]byte, []int) {
	return file_platform_report_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadExportRequest) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

func (x *DownloadExportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Response for downloading an export file (streaming). First message contains metadata,
// subsequent messages contain file chunks.
type DownloadExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*DownloadExportResponse_Metadata
	//	*DownloadExportResponse_Chunk
	Data isDownloadExportResponse_Data `protobuf_oneof:"data"`
}

func (x *DownloadExportResponse) Reset() {
	*x = DownloadExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_report_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportResponse) ProtoMessage() {}

func (x *DownloadExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_report_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportResponse.ProtoReflect.Descriptor instead.
func (*DownloadExportResponse) Descriptor() ([]byte, []int) {
	return file_platform_report_proto_rawDescGZIP(), []int{4}
}

func (m *DownloadExportResponse) GetData() isDownloadExportResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *DownloadExportResponse) GetMetadata() *DownloadMetadata {
	if x, ok := x.GetData().(*DownloadExportResponse_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *DownloadExportResponse) GetChunk() []byte {
	if x, ok := x.GetData().(*DownloadExportResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isDownloadExportResponse_Data interface {
	isDownloadExportResponse_Data()
}

type DownloadExportResponse_Metadata struct {
	Metadata *DownloadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DownloadExportResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*DownloadExportResponse_Metadata) isDownloadExportResponse_Data() {}

func (*DownloadExportResponse_Chunk) isDownloadExportResponse_Data() {}

var File_platform_report_proto protoreflect.FileDescriptor

var file_platform_report_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x02,
	0x0a, 0x09, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0xc9, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x62, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6a, 0x6f, 0x62, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62,
	0x73, 0x22, 0x51, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x16, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x85, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x1f, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x2d, 0x6a, 0x6f, 0x62, 0x73, 0x12, 0x84, 0x01, 0x0a, 0x0e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x12, 0x25, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x2d, 0x6a, 0x6f, 0x62, 0x73, 0x2f, 0x7b, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x30, 0x01,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x64, 0x61, 0x72, 0x6b, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x34, 0x2f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_report_proto_rawDescOnce sync.Once
	file_platform_report_proto_rawDescData = file_platform_report_proto_rawDesc
)

func file_platform_report_proto_rawDescGZIP() []byte {
	file_platform_report_proto_rawDescOnce.Do(func() {
		file_platform_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_report_proto_rawDescData)
	})
	return file_platform_report_proto_rawDescData
}

var file_platform_report_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_platform_report_proto_goTypes = []any{
	(*ExportJob)(nil),              // 0: platform.ExportJob
	(*ListExportJobsRequest)(nil),  // 1: platform.ListExportJobsRequest
	(*ListExportJobsResponse)(nil), // 2: platform.ListExportJobsResponse
	(*DownloadExportRequest)(nil),  // 3: platform.DownloadExportRequest
	(*DownloadExportResponse)(nil), // 4: platform.DownloadExportResponse
	(ExportType)(0),                // 5: platform.ExportType
	(ExportStatus)(0),              // 6: platform.ExportStatus
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*DownloadMetadata)(nil),       // 8: platform.DownloadMetadata
}
var file_platform_report_proto_depIdxs = []int32{
	5,  // 0: platform.ExportJob.export_type:type_name -> platform.ExportType
	6,  // 1: platform.ExportJob.status:type_name -> platform.ExportStatus
	7,  // 2: platform.ExportJob.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: platform.ExportJob.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: platform.ListExportJobsRequest.export_type:type_name -> platform.ExportType
	6,  // 5: platform.ListExportJobsRequest.status:type_name -> platform.ExportStatus
	0,  // 6: platform.ListExportJobsResponse.jobs:type_name -> platform.ExportJob
	8,  // 7: platform.DownloadExportResponse.metadata:type_name -> platform.DownloadMetadata
	1,  // 8: platform.ReportService.ListExportJobs:input_type -> platform.ListExportJobsRequest
	3,  // 9: platform.ReportService.DownloadExport:input_type -> platform.DownloadExportRequest
	2,  // 10: platform.ReportService.ListExportJobs:output_type -> platform.ListExportJobsResponse
	4,  // 11: platform.ReportService.DownloadExport:output_type -> platform.DownloadExportResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_platform_report_proto_init() }
func file_platform_report_proto_init() {
	if File_platform_report_proto != nil {
		return
	}
	file_platform_shared_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_platform_report_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExportJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_report_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListExportJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_report_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListExportJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_report_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_report_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DownloadExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_platform_report_proto_msgTypes[4].OneofWrappers = []any{
		(*DownloadExportResponse_Metadata)(nil),
		(*DownloadExportResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_report_proto_goTypes,
		DependencyIndexes: file_platform_report_proto_depIdxs,
		MessageInfos:      file_platform_report_proto_msgTypes,
	}.Build()
	File_platform_report_proto = out.File
	file_platform_report_proto_rawDesc = nil
	file_platform_report_proto_goTypes = nil
	file_platform_report_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportServiceClient interface {
	// List async export jobs for the tenant.
	ListExportJobs(ctx context.Context, in *ListExportJobsRequest, opts ...grpc.CallOption) (*ListExportJobsResponse, error)
	// Download a completed export file (server streaming).
	DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (ReportService_DownloadExportClient, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) ListExportJobs(ctx context.Context, in *ListExportJobsRequest, opts ...grpc.CallOption) (*ListExportJobsResponse, error) {
	out := new(ListExportJobsResponse)
	err := c.cc.Invoke(ctx, "/platform.ReportService/ListExportJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (ReportService_DownloadExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReportService_serviceDesc.Streams[0], "/platform.ReportService/DownloadExport", opts...)
	if err != nil {
		return nil, err
	}
	x := &reportServiceDownloadExportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReportService_DownloadExportClient interface {
	Recv() (*DownloadExportResponse, error)
	grpc.ClientStream
}

type reportServiceDownloadExportClient struct {
	grpc.ClientStream
}

func (x *reportServiceDownloadExportClient) Recv() (*DownloadExportResponse, error) {
	m := new(DownloadExportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReportServiceServer is the server API for ReportService service.
type ReportServiceServer interface {
	// List async export jobs for the tenant.
	ListExportJobs(context.Context, *ListExportJobsRequest) (*ListExportJobsResponse, error)
	// Download a completed export file (server streaming).
	DownloadExport(*DownloadExportRequest, ReportService_DownloadExportServer) error
}

// UnimplementedReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (*UnimplementedReportServiceServer) ListExportJobs(context.Context, *ListExportJobsRequest) (*ListExportJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExportJobs not implemented")
}
func (*UnimplementedReportServiceServer) DownloadExport(*DownloadExportRequest, ReportService_DownloadExportServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadExport not implemented")
}

func RegisterReportServiceServer(s *grpc.Server, srv ReportServiceServer) {
	s.RegisterService(&_ReportService_serviceDesc, srv)
}

func _ReportService_ListExportJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExportJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ListExportJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.ReportService/ListExportJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ListExportJobs(ctx, req.(*ListExportJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_DownloadExport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReportServiceServer).DownloadExport(m, &reportServiceDownloadExportServer{stream})
}

type ReportService_DownloadExportServer interface {
	Send(*DownloadExportResponse) error
	grpc.ServerStream
}

type reportServiceDownloadExportServer struct {
	grpc.ServerStream
}

func (x *reportServiceDownloadExportServer) Send(m *DownloadExportResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "platform.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExportJobs",
			Handler:    _ReportService_ListExportJobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadExport",
			Handler:       _ReportService_DownloadExport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "platform/report.proto",
}
